version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Пробрасываем текущую папку проекта в контейнер
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=ipcheck_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ipcheck_db
    ports:
      - "5432:5432"
    volumes:
      # Создаст папку 'pgdata' прямо внутри рабочей папки ipcheck! 📁
      - ./pgdata:/var/lib/postgresql/data
