steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart Docker Container
        run: |
          docker compose down || true
          docker compose up -d --build
