name: Deploy to Local Test Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: |
          cd /home/muhammad_muminov/project/ipcheck
          docker compose down
          docker compose up -d --build
